### ISSUE TITLE
postgresql_query fails with 'can't execute an empty query' when a commented out query is present in the script

### ISSUE THREAD

**Issue by nodiscc** [ansible-collections/community.postgresql#50] opened 2021-01-31 12:58 UTC
##### SUMMARY

When trying to run [this script](https://git.tt-rss.org/fox/tt-rss/src/branch/master/schema/ttrss_schema_pgsql.sql) through `postgresql_query` using `path_to_script`, the module fails with

```
Cannot execute SQL: -- create index ttrss_entries_title_index on ttrss_entries(title)' None: can't execute an empty query, query list:
[...]
```

Deleting the commented-out query line 164 makes the module work again.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`posqtgresql_query`

##### ANSIBLE VERSION

```paste below
ansible 2.10.5
  config file = None
  configured module search path = ['/home/live/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/live/.local/share/xsrv/venv/lib/python3.7/site-packages/ansible
  executable location = /home/live/.local/share/xsrv/venv/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

- Debian 10 Buster on host and controller
- postgresql 11+200+deb10u4

##### STEPS TO REPRODUCE

```yaml
# playbook.yml
- hosts: my.EXAMPLE.org
  roles:
    - tt_rss

# roles/tt_rss/tasks/main.yml
- include: tt-rss.yml
  become: yes

# roles/tt_rss/tasks/tt-rss.yml
- name: install postgresql
  apt:
    state: present
    package:
      - postgresql
      - postgresql-client

- name: install packages for postgresql support
  apt:
    state: present
    package:
      - php-pgsql
      - python3-psycopg2

- name: create tt-rss postgresql user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ttrss"
    state: present

- name: set tt-rss postgresql user password
  become: yes
  become_user: postgres
  postgresql_user:
    name: "ttrss"
    password: "CHANGEME"
  no_log: True

- name: create tt-rss postgresql database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "ttrss"
    state: present
    encoding: 'UNICODE'
    owner: 'ttrss'

- name: grant privileges on tt-rss database to tt-rss postgresql user
  become: yes
  become_user: postgres
  postgresql_privs:
    db: "ttrss"
    privs: ALL
    type: database
    role: "ttrss"

- name: clone/upgrade tt-rss
  git:
    repo: https://git.tt-rss.org/git/tt-rss.git
    dest: "/var/www/rss.EXAMPLE.org"
    version: 'master'
    accept_hostkey: yes
    force: yes

- name: import tt-rss database schema to postgresql
  postgresql_query:
    login_host: "localhost"
    login_user: "ttrss"
    login_password: "CHANGEME"
    db: "ttrss"
    path_to_script: "/var/www/rss.EXAMPLE.org/schema/ttrss_schema_pgsql.sql"


```

##### EXPECTED RESULTS

The commented out line should be ignored and the script should execute correctly. Note that running the script with `sudo -u postgres psql --file=/var/www/rss.EXAMPLE.org/schema/ttrss_schema_pgsql.sql` works without problems.

##### ACTUAL RESULTS

```paste below
$ ansible-playbook playbook.yml

[...]

TASK [tt_rss : import tt-rss database schema to postgresql] *************************************************************************************************************
fatal: [my.EXAMPLE.org]: FAILED! => {
    "changed": false
}

MSG:

Cannot execute SQL '

-- create index ttrss_entries_title_index on ttrss_entries(title)' None: can't execute an empty query, query list: ['drop table if exists ttrss_error_log', '\ndrop table if exists ttrss_plugin_storage', '\ndrop table if exists ttrss_linked_feeds', '...................
```

Inserting the following task before `import tt-rss database schema to postgresql` makes the playbook work again:

```yaml
- name: remove comments from SQL schema file
  lineinfile:
    path: "{{ tt_rss_install_dir }}/schema/ttrss_schema_pgsql.sql"
    state: absent
    regexp: '^--.*'
```

**Comment by Andersson007** [comment] 2021-02-01 06:37
@nodiscc thanks for reporting the issue!
CC @Dorn- @andytom @ilicmilan @kostiantyn-nemchenko @matburt @nerzhul @sebasmannem @tcraxs

**Comment by Andersson007** [comment] 2021-02-01 11:46
@nodiscc have you tried `as_single_query: yes` option?

**Comment by nodiscc** [comment] 2021-02-21 10:49
sorry for the delay, I just tried with `as_single_query: yes` and am getting an error:

```
fatal: [my.CHANGEME.org]: FAILED! => {
    "changed": false
}

MSG:

Unsupported parameters for (postgresql_query) module: as_single_query Supported parameters include: autocommit, ca_cert, db, encoding, login_host, login_password, login_unix_socket, login_user, named_args, path_to_script, port, positional_args, query, search_path, session_role, ssl_mode, trust_input
```

Same result after upgrading to ansible 2.10.7

**Comment by Andersson007** [comment] 2021-02-22 06:49
@nodiscc about the delay - no problem at all! Thanks for the feedback!

Could you please change the module invocation in your playbook to use FQCN (fully qualified collection name) `postgresql_query:` => `community.postgresql.postgresql_query:` ?

**Comment by Andersson007** [comment] 2021-03-12 06:36
@nodiscc hi, if you try what i suggested ^ and give feedback, I would be really grateful:)

**Comment by Andersson007** [comment] 2021-03-24 06:27
@nodiscc thanks for the feedback
I added a couple of comments `-- bla bla` to out tests scripts.
With `as_single_query: no` it fails but with different error (as expected),
and with `as_single_query: yes` it passed, so can't reproduce.

Could you please share your script again? I don't see it using the link in the description. Maybe it was removed.

**Comment by nodiscc** [comment] 2021-04-01 16:21
The file has moved: https://git.tt-rss.org/fox/tt-rss/src/branch/master/sql/pgsql/schema.sql


[schema.sql](https://github.com/ansible-collections/community.postgresql/files/6244943/schema.sql.txt)

**Comment by Andersson007** [comment] 2021-04-02 06:12
@nodiscc thanks for the script!

I took it as it is and ran with the following task:
```
 33 # Issue https://github.com/ansible-collections/community.postgresql/issues/50
 34 - name: postgresql_query - run queries from SQL script
 35   become_user: '{{ pg_user }}'
 36   become: true
 37   community.postgresql.postgresql_query:
 38     login_user: '{{ pg_user }}'
 39     db: postgres
 40     path_to_script: ~{{ pg_user }}/test2.sql
 41     encoding: UTF-8
 42     as_single_query: yes
 43   register: result
```
The test has passed.
I use the latest collection version.
Could you install the latest version manually and try: https://galaxy.ansible.com/community/postgresql , How to is https://docs.ansible.com/ansible/latest/user_guide/collections_using.html

Thank you for the collaboration! Will be waiting feedback from you

**Comment by Andersson007** [comment] 2021-04-02 06:51
(this options is a source of pain actually. i'd recommend to use `postgresql_db` with `state: restore` whenever possible)

**Comment by nodiscc** [comment] 2021-04-09 18:22
```diff
--- a/ansible_collections/nodiscc/xsrv/roles/tt_rss/tasks/tt-rss.yml
+++ b/ansible_collections/nodiscc/xsrv/roles/tt_rss/tasks/tt-rss.yml
@@ -93,20 +93,21 @@
 ### INITIAL DB POPULATION ###
 
- # workaround for postgresql_query module bug https://github.com/ansible-collections/community.postgresql/issues/50
-- name: remove comments from SQL schema file
-  lineinfile:
-    path: "{{ tt_rss_install_dir }}/sql/pgsql/schema.sql"
-    state: absent
-    regexp: '^--.*'
-  when: (ansible_local.tt_rss.general.db_imported is not defined) or (not ansible_local.tt_rss.general.db_imported)

 - name: import tt-rss database schema to postgresql
-  postgresql_query:
+  community.postgresql.postgresql_query:
     login_host: "localhost"
     login_user: "{{ tt_rss_db_user }}"
     login_password: "{{ tt_rss_db_password }}"
     db: "{{ tt_rss_db_name }}"
     path_to_script: "{{ tt_rss_install_dir }}/sql/pgsql/ttrss_schema_pgsql.sql"
+    as_single_query: yes
   when: (ansible_local.tt_rss.general.db_imported is not defined) or (not ansible_local.tt_rss.general.db_imported)
 
 - name: update tt-rss admin account in postgresql database (always returns changed)
diff --git a/requirements.yml b/requirements.yml
index c4596d4..c48ebfe 100644
--- a/requirements.yml
+++ b/requirements.yml
@@ -2,3 +2,6 @@ collections:
   - name: https://gitlab.com/nodiscc/xsrv.git
     type: git
     version: monitoring-netdata-httpcheck-conf-d
+  - name: https://github.com/ansible-collections/community.postgresql
+    type: git
+    version: main
~
```

```bash
$ ansible-galaxy collection install --force -r requirements.yml
$ ansible-playbook playbook.yml --tags=tt-rss
```

-> it works. Thank you @Andersson007 

I can live with the workaround for now and I'd prefer to avoid using a development version of `community.postgresql` in my playbooks. How/when will the collection be updated in the [ansible pypi distribution](https://pypi.org/project/ansible/)? In the next release?

thanks again

**Comment by Andersson007** [comment] 2021-04-10 04:44
@nodiscc yes, in the next release of Ansible 3 it should be there.
It's not a dev version, it's an official release and Ansible just picks up all the tarballs (latest versions) of the collections included in the package. It's just my opinion but this approach gives flexibility when we can install minimal ansible-core + collections from galaxy we really needed (not all ~80 included by default). Anyway:)
I'll close the issue then.
@nodiscc thanks for the feedback!

**Closed by Andersson007** 2021-04-10 04:44 UTC
