### ISSUE TITLE
Multiple queries should return multiple results

### ISSUE THREAD

**Issue by felipenazario** [ansible-collections/community.postgresql#758] opened 2024-10-22 14:33 UTC
##### SUMMARY
Sometime ago I opened the issue 312 and I it is marked as closed and resolved, but it keeps the same behavior as before. I **still** believe that if the script file has N SQL queries, it should return N results. But today it only returns the last SQL Query in the script file.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_script

##### ANSIBLE VERSION

```sh
ansible [core 2.17.5]
  config file = /home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg
  configured module search path = ['/home/nazario/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nazario/workspace_infra/MyCode/.pyenv_for_3.13.0/lib/python3.13/site-packages/ansible
  ansible collection location = /opt/ansible/collections:/home/nazario/workspace_infra/MyCode/ansible/linux/collections
  executable location = /home/nazario/workspace_infra/MyCode/.pyenv_for_3.13.0/bin/ansible
  python version = 3.13.0 (main, Oct  9 2024, 11:03:32) [GCC 7.5.0] (/home/nazario/workspace_infra/MyCode/.pyenv_for_3.13.0/bin/python)
  jinja version = 3.1.4
  libyaml = False
```

##### COLLECTION VERSION

```sh
Collection                               Version
---------------------------------------- -------
ansible.eda                              2.2.0  
ansible.netcommon                        7.1.0  
ansible.posix                            1.6.1  
ansible.utils                            5.1.2  
ansible.windows                          2.5.0  
chocolatey.chocolatey                    1.5.3  
community.crypto                         2.22.2 
community.digitalocean                   1.27.0 
community.docker                         3.13.1 
community.general                        9.5.0  
community.library_inventory_filtering_v1 1.0.1  
community.mysql                          3.10.3 
community.postgresql                     3.7.0  
community.windows                        2.3.0  
containers.podman                        1.16.1 
cyberark.conjur                          1.3.0  
dellemc.os6                              1.0.7  
dellemc.os9                              1.0.4  
digitalocean.cloud                       0.6.0  
kubernetes.core                          5.0.0  
oracle.oci                               5.3.0
```

##### CONFIGURATION

```txt
CALLBACKS_ENABLED(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = ['ansible.posix.timer', 'ansible.posix.profile_roles', 'ansible.posix.profile_tasks', 'ansible.builtin.oneline']
COLLECTIONS_PATHS(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = ['/opt/ansible/collections', '/home/nazario/workspace_infra/MyCode/ansible/linux/collections']
CONFIG_FILE() = /home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg
DEFAULT_FORKS(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = ['/home/nazario/workspace_infra/MyCode/ansible/linux/inventories/vagrant/hosts.ini']
DEFAULT_PRIVATE_ROLE_VARS(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = True
DEFAULT_ROLES_PATH(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = ['/opt/ansible/roles', '/home/nazario/workspace_infra/MyCode/ansible/linux/roles']
DEFAULT_TIMEOUT(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = 15
DEFAULT_VAULT_IDENTITY_LIST(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = ['prod@keys/ansible_vault/prod.sec']
DEPRECATION_WARNINGS(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = True
HOST_KEY_CHECKING(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = False
INTERPRETER_PYTHON(/home/nazario/workspace_infra/MyCode/ansible/linux/ansible.cfg) = auto
```

##### OS / ENVIRONMENT

uname -a

```txt
Linux localhost.localdomain 5.3.18-150300.59.106-default #1 SMP Mon Dec 12 13:16:24 UTC 2022 (774239c) x86_64 x86_64 x86_64 GNU/Linux
```

cat /etc/os-release

```txt
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

##### STEPS TO REPRODUCE

```yaml
- name: 'Create test file.'
  ansible.builtin.lineinfile:
    create: true
    path: "/tmp/test.sql"
    regexp: '^'
    line: >-
      select current_database();
      select now();
      select version();
      select usename from pg_catalog.pg_user;

- name: "Query"
  community.postgresql.postgresql_script:
    login_db: "postgres"
    login_user: "postgres"
    login_password: "123"
    login_port: 5432
    path: "/tmp/test.sql"
  register: output

- name: "Print var."
  ansible.builtin.debug:
    msg: "{{ output }}"
```

##### EXPECTED RESULTS

```txt
ok: [postgres_origin] => {
    "msg": {
        "changed": true,
        "failed": false,
        "query": "select current_database();\nselect now();\nselect version();\nselect usename from pg_catalog.pg_user;\n",
        "query_result": [
            {
                "current_database": "postgres",
                "rowcount": 1,
                "statusmessage": "SELECT 1"
            },
            {
                "now": "2024-10-22T14:22:19.337865+00:00"
                "rowcount": 1,
                "statusmessage": "SELECT 1"
            },
            {
                "version": "PostgreSQL 14.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit"
                "rowcount": 1,
                "statusmessage": "SELECT 1"
            },
            {
                "usename": "postgres",
                "usename": "reader"
                "rowcount": 2,
                "statusmessage": "SELECT 1"
            }
        ]
    }
}
```

##### ACTUAL RESULTS

```txt
ok: [postgres_origin] => {
    "msg": {
        "changed": true,
        "failed": false,
        "query": "select current_database();\nselect now();\nselect version();\nselect usename from pg_catalog.pg_user;\n",
        "query_result": [
            {
                "usename": "postgres"
                "usename": "reader"
            }
        ],
        "rowcount": 2,
        "statusmessage": "SELECT 1"
    }
}
```

**Comment by Andersson007** [comment] 2024-10-23 08:30
@felipenazario thanks for opening the issue. The concerns raised in #312 are still valid.
In particular, if in the `postgresql_query` module you can pass your queries as a list, so there's no problem with determining when one query starts and ends: it's just an element of the list and the module executes them one by one and appends the result.
With the `postgresql_script` we should also create a list of queries first to be able to append the result of each query and return it, however:
1. the problem is that how to do it. you can't just use ";" because it can appear as a part of strings passed in the query like "SELECT blah FROM test_table WHERE blah = 'my text ; ' AND blah != ' ; another text containing semicolons' ... ; SELECT .."
2. even if there's a sophisticated solution for this issue, it'd make the logic and the code more complicated and error-prone.

So if the getting a result of each query is important for a user, I would suggest using `postgresql_query` instead.
If the user wants to get queries from a file, I think they can use the lookup plugin to fetch it and then other plugins to transform it to the yml list and pass it to the `_query` module

**Comment by felipenazario** [comment] 2024-10-23 12:47
Hi @Andersson007,

Nice to talk to you again, the last the we [talked](https://github.com/ansible-collections/community.postgresql/issues/312#issuecomment-1222839247), I said...

> As you already figure out, we do not split multiple queries in the same position. At least for now, when somebody send a Pull Request providing a special regex to find all query delimiters in all scenarios, it would be merged.

Below there is something to **try** the correct split.

```python
import re

sql = "SELECT * FROM users; INSERT INTO users (name) VALUES ('John; Doe'); DELETE FROM users WHERE id = 1;INSERT INTO text VALUES ('my text ; blah ; blah'); SELECT 1"
statements = re.split(r';(?=(?:[^"\'"]|"[^"]*"|\'[^\']*\')*$)', sql)

# Remove empty strings and strip spaces
statements = [s.strip() for s in statements if s.strip()]

for statement in statements:
    print(statement)
```

Let me know what do you think of it. Meanwhile, I will be looking for what you suggested.

> if the user wants to get queries from a file, I think they can use the lookup plugin to fetch it and then other plugins to transform it to the yml list and pass it to the _query module

**Comment by Andersson007** [comment] 2024-10-25 07:19
@felipenazario this approach is unfortunately error prone, you can easily get something like
```
SELECT * FROM users; INSERT INTO users (name) VALUES ('John
Doe'); DELETE FROM users WHERE id = 1;INSERT INTO text VALUES ('
my te
xt
blah
blah'); insert into test values ($$escape ;'
SELECT 1
with ''$$)
SELECT 1
```
Regexps are not the options imo, there's a need for a don't-know-how-to-complex parser here

**Comment by felipenazario** [comment] 2024-10-25 13:04
Hi @Andersson007, you are right the Regex expressions has its limitations. I asked to ChatGPT using the model o1-preview a better version of the first program. It created an even more complex SQL input that pushes the limits of the **split_sql_statements** function. This new version will include:

- Nested multi-line comments
- Comments within strings
- Strings within comments
- Backslash escapes
- Copy commands with data blocks
- Complex function definitions with language variations
- JSON and XML data types
- Use of custom operators and domains
- Arrays and composite types
- C-style comments inside strings
- Procedural code with control structures

```python
import re

class SQLParsingError(Exception):
    def __init__(self, message, position):
        super().__init__(f"{message} at position {position}")

sql = """
SELECT * FROM users; INSERT INTO users (name) VALUES ('John
Doe'); DELETE FROM users WHERE id = 1;INSERT INTO text VALUES ('
my te
xt
blah
blah'); insert into test values ($$escape ;'
SELECT 1
with ''$$);
SELECT 1;

-- Outer comment
/* Multi-line comment start
   /* Nested comment */
   Still in comment
*/
CREATE DOMAIN positive_int AS INTEGER CHECK (VALUE > 0);

CREATE TYPE complex_number AS (
    real DOUBLE PRECISION,
    imaginary DOUBLE PRECISION
);

CREATE TABLE complex_table (
    id SERIAL PRIMARY KEY,
    number complex_number,
    tags TEXT[]
);

INSERT INTO complex_table (number, tags) VALUES
    ((1.0, -1.0), ARRAY['first', 'number']),
    ((2.0, -2.0), ARRAY['second', 'number; with semicolon']),
    ((3.0, -3.0), ARRAY['third', 'number /* comment inside tag */']);

-- Copy command with data block containing semicolons and quotes
COPY complex_table (number, tags) FROM STDIN;
(4.0,-4.0)  {fourth,"number with ""quotes"" and ; semicolon"}
\.

CREATE OR REPLACE FUNCTION complex_function()
RETURNS VOID AS $$
DECLARE
    v_record RECORD;
BEGIN
    FOR v_record IN SELECT * FROM complex_table LOOP
        RAISE NOTICE 'Processing id: %, number: %', v_record.id, v_record.number;
        -- Simulate processing
        PERFORM pg_sleep(0.1);
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Function with language SQL and complex body
CREATE FUNCTION json_example() RETURNS JSON AS $json_func$
SELECT json_build_object(
    'array', json_agg(row_to_json(t))
)
FROM (
    SELECT id, number, tags FROM complex_table
) t;
$json_func$ LANGUAGE SQL;

-- XML example
SELECT XMLELEMENT(NAME "Test", XMLATTRIBUTES(id AS "ID"), number::text) FROM complex_table;

-- Complex procedural code with nested quotes and comments
DO $do$
BEGIN
    EXECUTE $f$SELECT * FROM complex_table WHERE tags @> ARRAY[$tag$number; with semicolon$tag$]$f$;
    -- Nested DO block
    DO $$ BEGIN
        RAISE NOTICE 'Nested DO block';
    END $$;
END;
$do$;

-- Edge case: Semicolons inside backslash-escaped strings
SELECT 'Backslash escaped quote: \\' and semicolon: ;';

-- Edge case: C-style comment inside a string
SELECT 'String with /* not a comment */ inside';

-- Edge case: Unclosed string
-- SELECT 'This string is not closed;

-- Edge case: Dollar-quoted string with tag containing special characters
SELECT $ta$This is a dollar-quoted string with tag containing special characters ta$ta$;

-- Edge case: Empty dollar-quoted string
-- SELECT $$;

-- Edge case: Multi-byte characters
SELECT 'Unicode test: 測試, テスト, اختبار';

-- Edge case: Comments with semicolons and quotes
/* This is a comment with a semicolon; and a 'quote' */
-- This is a single-line comment with a semicolon; and a "double quote"

-- Final simple statement
SELECT * FROM complex_table;
"""

def split_sql_statements(sql):
    statements = []
    statement = ''
    in_single_quote = False
    in_double_quote = False
    in_e_string = False
    in_dollar_quote = False
    dollar_quote_tag = ''
    in_single_line_comment = False
    in_multi_line_comment = 0  # Counter for nested comments
    in_copy_data = False
    copy_data_terminator = ''
    i = 0
    length = len(sql)
    while i < length:
        char = sql[i]
        next_char = sql[i+1] if i+1 < length else ''
        position = i
        if in_single_line_comment:
            if char == '\n':
                in_single_line_comment = False
                statement += char
            else:
                statement += char
        elif in_multi_line_comment > 0:
            if char == '/' and next_char == '*':
                in_multi_line_comment += 1
                statement += '/*'
                i += 1
            elif char == '*' and next_char == '/':
                in_multi_line_comment -= 1
                statement += '*/'
                i += 1
            else:
                statement += char
        elif in_copy_data:
            # Handle COPY data until the terminator is found
            if sql[i:i+len(copy_data_terminator)] == copy_data_terminator:
                statement += copy_data_terminator
                i += len(copy_data_terminator) - 1
                in_copy_data = False
            else:
                statement += char
        elif in_dollar_quote:
            # Check for the end of dollar-quoted string
            if sql[i:i+len(dollar_quote_tag)] == dollar_quote_tag:
                statement += dollar_quote_tag
                i += len(dollar_quote_tag) - 1
                in_dollar_quote = False
            else:
                statement += char
        elif in_e_string:
            if char == "\\":
                # Handle backslash escape in E-strings
                if next_char:
                    statement += char + next_char
                    i += 1
                else:
                    statement += char
            elif char == "'":
                statement += char
                in_e_string = False
            else:
                statement += char
        elif in_single_quote:
            if char == "\\":
                # Handle backslash escape in strings (optional, depending on standard_conforming_strings)
                if next_char:
                    statement += char + next_char
                    i += 1
                else:
                    statement += char
            elif char == "'":
                statement += char
                in_single_quote = False
            else:
                statement += char
        elif in_double_quote:
            if char == '"':
                statement += char
                in_double_quote = False
            else:
                statement += char
        else:
            # Not inside any quotes or comments
            if char == '-' and next_char == '-':
                in_single_line_comment = True
                statement += '--'
                i += 1
            elif char == '/' and next_char == '*':
                in_multi_line_comment += 1
                statement += '/*'
                i += 1
            elif char == "'":
                statement += char
                in_single_quote = True
            elif char == '"':
                statement += char
                in_double_quote = True
            elif char == 'E' and next_char == "'":
                statement += 'E\''
                i += 1
                in_e_string = True
            elif char == '$':
                # Start of dollar-quoted string
                m = re.match(r'\$([A-Za-z0-9_]*)\$', sql[i:])
                if m:
                    dollar_quote_tag = m.group()
                    statement += dollar_quote_tag
                    i += len(dollar_quote_tag) - 1
                    in_dollar_quote = True
                else:
                    statement += char
            elif re.match(r'COPY\b', sql[i:], re.IGNORECASE):
                # Start of COPY command, check for FROM or TO STDIN/STDOUT
                m = re.match(r'COPY\b.*?(FROM|TO)\s+(STDIN|STDOUT)\b', sql[i:], re.IGNORECASE | re.DOTALL)
                if m:
                    copy_data_terminator = '\.\n'
                    copy_match = m.group()
                    statement += copy_match
                    i += len(copy_match) - 1
                    in_copy_data = True
                else:
                    statement += char
            elif char == ';':
                # End of statement
                if in_multi_line_comment > 0 or in_single_quote or in_double_quote or in_dollar_quote or in_e_string:
                    raise SQLParsingError("Unclosed quote or comment", position)
                statements.append(statement.strip())
                statement = ''
            else:
                statement += char
        i += 1

    if in_single_quote:
        raise SQLParsingError("Unclosed single quote", length)
    if in_double_quote:
        raise SQLParsingError("Unclosed double quote", length)
    if in_dollar_quote:
        raise SQLParsingError("Unclosed dollar-quoted string", length)
    if in_e_string:
        raise SQLParsingError("Unclosed E-string", length)
    if in_multi_line_comment > 0:
        raise SQLParsingError("Unclosed multi-line comment", length)
    if in_copy_data:
        raise SQLParsingError("Unclosed COPY data block", length)

    if statement.strip():
        statements.append(statement.strip())
    return statements

try:
    statements = split_sql_statements(sql)
    for idx, statement in enumerate(statements, 1):
        print(f"Statement {idx}:\n{statement}\n{'-'*80}")
except SQLParsingError as e:
    print(f"Error parsing SQL: {e}")
```

## **Additional Considerations for PostgreSQL Dialect**

1. **Standard Conforming Strings:**
   - PostgreSQL can be configured to interpret backslash escapes differently based on the `standard_conforming_strings` setting.
   - Our parser assumes `standard_conforming_strings` is off for backslash escapes in strings.
   - Adjusting for different settings requires more context and is beyond the scope of this parser.

2. **Dollar-Quoted String Tags:**
   - PostgreSQL allows almost any character in dollar-quote tags.
   - Our regex `\$([^\$]*)\$` captures any sequence between `$` and `$`, excluding the `$` character itself.
   - This supports a wide range of tags but might need adjustments for edge cases with special characters.

3. **Unicode and Multi-byte Characters:**
   - The parser operates on the string as a sequence of characters and should handle Unicode without issues.

4. **Custom Operators and Syntax:**
   - PostgreSQL allows for custom operators and complex expressions.
   - As long as these do not interfere with the parsing of quotes, comments, or statement terminators, the parser should handle them correctly.

## **Conclusion**

The enhanced `split_sql_statements` function now:

- Detects unclosed quotes and comments, raising informative errors with positions.
- Supports PostgreSQL-specific syntax and features, including nested comments, E-strings, and COPY commands with data blocks.
- Handles complex SQL inputs with various edge cases.

**Note:** This parser provides a reasonable approximation for splitting SQL scripts but is not a full SQL parser. For production use, consider leveraging existing libraries or tools designed for parsing SQL according to the full syntax rules of PostgreSQL.

**Comment by Andersson007** [comment] 2024-10-29 09:05
@felipenazario thanks for investigating!
A full SQL parser would be the away to go but my personal opinion is that it's not worth it in our case.
Even this one by ChatGPT, not sure i'd like to maintain it when related bug reports show up;) I'm sure they'll show up

**Comment by felipenazario** [comment] 2024-10-29 15:17
I understand your point, but since this functionality is for a long time missing and it could be reused in the modules of [postgresql_query](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_query_module.html) and [postgresql_script](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_script_module.html). I will gently insist in this new refactored code below. I hope this could easy the maintenance of this function.

```python
import re

class SQLParsingError(Exception):
    def __init__(self, message, position):
        super().__init__(f"{message} at position {position}")

class SQLParser:
    def __init__(self, sql_text):
        self._sql = sql_text
        self._statements = []
        self._statement = ''
        self._position = 0
        self._length = len(sql_text)

        # Flags and states
        self._in_single_quote = False
        self._in_double_quote = False
        self._in_e_string = False
        self._in_dollar_quote = False
        self._dollar_quote_tag = ''
        self._in_single_line_comment = False
        self._in_multi_line_comment = 0
        self._in_copy_data = False
        self._copy_data_terminator = ''

    def parse(self):
        while self._position < self._length:
            char = self._sql[self._position]
            next_char = self._peek()

            if self._in_single_line_comment:
                self._handle_single_line_comment(char)
            elif self._in_multi_line_comment > 0:
                self._handle_multi_line_comment(char, next_char)
            elif self._in_copy_data:
                self._handle_copy_data()
            elif self._in_dollar_quote:
                self._handle_dollar_quote()
            elif self._in_e_string:
                self._handle_e_string(char, next_char)
            elif self._in_single_quote:
                self._handle_single_quote(char, next_char)
            elif self._in_double_quote:
                self._handle_double_quote(char)
            else:
                self._handle_general_cases(char, next_char)
            self._position += 1

        self._validate_closures()
        if self._statement.strip():
            self._statements.append(self._statement.strip())

        return self._statements

    def _peek(self):
        return self._sql[self._position + 1] if self._position + 1 < self._length else ''

    def _handle_single_line_comment(self, char):
        if char == '\n':
            self._in_single_line_comment = False
        self._statement += char

    def _handle_multi_line_comment(self, char, next_char):
        if char == '/' and next_char == '*':
            self._in_multi_line_comment += 1
            self._position += 1
        elif char == '*' and next_char == '/':
            self._in_multi_line_comment -= 1
            self._position += 1
        self._statement += char

    def _handle_copy_data(self):
        # Detect the end of the COPY data section by matching "\." at the start of a new line
        end_marker = '\n\\.'
        if self._sql[self._position:self._position + len(end_marker)] == end_marker or self._sql[self._position:self._position + len(self._copy_data_terminator)] == self._copy_data_terminator:
            # Add the end marker to the statement and end the COPY data mode
            self._statement += end_marker
            self._position += len(end_marker) - 1
            self._in_copy_data = False
        else:
            # Continue adding characters as part of the COPY data block
            self._statement += self._sql[self._position]

    def _handle_dollar_quote(self):
        if self._sql[self._position:self._position + len(self._dollar_quote_tag)] == self._dollar_quote_tag:
            self._statement += self._dollar_quote_tag
            self._position += len(self._dollar_quote_tag) - 1
            self._in_dollar_quote = False
        else:
            self._statement += self._sql[self._position]

    def _handle_e_string(self, char, next_char):
        if char == "\\":
            self._statement += char + next_char
            self._position += 1
        elif char == "'":
            self._in_e_string = False
        self._statement += char

    def _handle_single_quote(self, char, next_char):
        if char == "\\":
            self._statement += char + next_char
            self._position += 1
        elif char == "'":
            self._in_single_quote = False
        self._statement += char

    def _handle_double_quote(self, char):
        if char == '"':
            self._in_double_quote = False
        self._statement += char

    def _handle_general_cases(self, char, next_char):
        if char == '-' and next_char == '-':
            self._in_single_line_comment = True
            self._position += 1
        elif char == '/' and next_char == '*':
            self._in_multi_line_comment += 1
            self._position += 1
        elif char == "'":
            self._in_single_quote = True
        elif char == '"':
            self._in_double_quote = True
        elif char == 'E' and next_char == "'":
            self._in_e_string = True
            self._position += 1
        elif char == '$':
            self._handle_dollar_quote_start()
        elif re.match(r'COPY\b', self._sql[self._position:], re.IGNORECASE):
            self._handle_copy_command()
        elif char == ';':
            self._finalize_statement()
        else:
            self._statement += char

    def _handle_dollar_quote_start(self):
        m = re.match(r'\$([A-Za-z0-9_]*)\$', self._sql[self._position:])
        if m:
            self._dollar_quote_tag = m.group()
            self._statement += self._dollar_quote_tag
            self._position += len(self._dollar_quote_tag) - 1
            self._in_dollar_quote = True
        else:
            self._statement += '$'

    def _handle_copy_command(self):
        m = re.match(r'COPY\b.*?(FROM|TO)\s+(STDIN|STDOUT)\b', self._sql[self._position:], re.IGNORECASE | re.DOTALL)
        if m:
            self._copy_data_terminator = r'\.\n'
            self._statement += m.group()
            self._position += len(m.group()) - 1
            self._in_copy_data = True

    def _finalize_statement(self):
        if self._in_multi_line_comment > 0 or self._in_single_quote or self._in_double_quote or self._in_dollar_quote or self._in_e_string:
            raise SQLParsingError("Unclosed quote or comment", self._position)
        self._statements.append(self._statement.strip())
        self._statement = ''

    def _validate_closures(self):
        if self._in_single_quote:
            raise SQLParsingError("Unclosed single quote", self._length)
        if self._in_double_quote:
            raise SQLParsingError("Unclosed double quote", self._length)
        if self._in_dollar_quote:
            raise SQLParsingError("Unclosed dollar-quoted string", self._length)
        if self._in_e_string:
            raise SQLParsingError("Unclosed E-string", self._length)
        if self._in_multi_line_comment > 0:
            raise SQLParsingError("Unclosed multi-line comment", self._length)
        if self._in_copy_data:
            raise SQLParsingError("Unclosed COPY data block", self._length)

# Usage
sql = r"""
SELECT * FROM users; INSERT INTO users (name) VALUES ('John
Doe'); DELETE FROM users WHERE id = 1;INSERT INTO text VALUES ('
my te
xt
blah
blah'); insert into test values ($$escape ;'
SELECT 1
with ''$$);
SELECT 1;

-- Outer comment
/* Multi-line comment start
   /* Nested comment */
   Still in comment
*/
CREATE DOMAIN positive_int AS INTEGER CHECK (VALUE > 0);

CREATE TYPE complex_number AS (
    real DOUBLE PRECISION,
    imaginary DOUBLE PRECISION
);

CREATE TABLE complex_table (
    id SERIAL PRIMARY KEY,
    number complex_number,
    tags TEXT[]
);

INSERT INTO complex_table (number, tags) VALUES
    ((1.0, -1.0), ARRAY['first', 'number']),
    ((2.0, -2.0), ARRAY['second', 'number; with semicolon']),
    ((3.0, -3.0), ARRAY['third', 'number /* comment inside tag */']);

-- Copy command with data block containing semicolons and quotes
COPY complex_table (number, tags) FROM STDIN;
(4.0,-4.0)  {fourth,"number with ""quotes"" and ; semicolon"}
\.

CREATE OR REPLACE FUNCTION complex_function()
RETURNS VOID AS $$
DECLARE
    v_record RECORD;
BEGIN
    FOR v_record IN SELECT * FROM complex_table LOOP
        RAISE NOTICE 'Processing id: %, number: %', v_record.id, v_record.number;
        -- Simulate processing
        PERFORM pg_sleep(0.1);
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Function with language SQL and complex body
CREATE FUNCTION json_example() RETURNS JSON AS $json_func$
SELECT json_build_object(
    'array', json_agg(row_to_json(t))
)
FROM (
    SELECT id, number, tags FROM complex_table
) t;
$json_func$ LANGUAGE SQL;

-- XML example
SELECT XMLELEMENT(NAME "Test", XMLATTRIBUTES(id AS "ID"), number::text) FROM complex_table;

-- Complex procedural code with nested quotes and comments
DO $do$
BEGIN
    EXECUTE $f$SELECT * FROM complex_table WHERE tags @> ARRAY[$tag$number; with semicolon$tag$]$f$;
    -- Nested DO block
    DO $$ BEGIN
        RAISE NOTICE 'Nested DO block';
    END $$;
END;
$do$;

-- Edge case: Semicolons inside backslash-escaped strings
SELECT 'Backslash escaped quote: \\' and semicolon: ;';

-- Edge case: C-style comment inside a string
SELECT 'String with /* not a comment */ inside';

-- Edge case: Unclosed string
-- SELECT 'This string is not closed;

-- Edge case: Dollar-quoted string with tag containing special characters
SELECT $ta$This is a dollar-quoted string with tag containing special characters ta$ta$;

-- Edge case: Empty dollar-quoted string
-- SELECT $$;

-- Edge case: Multi-byte characters
SELECT 'Unicode test: 測試, テスト, اختبار';

-- Edge case: Comments with semicolons and quotes
/* This is a comment with a semicolon; and a 'quote' */
-- This is a single-line comment with a semicolon; and a "double quote"

-- Final simple statement
SELECT * FROM complex_table;
"""

sql_parser = SQLParser(sql)
try:
    statements = sql_parser.parse()
    for idx, statement in enumerate(statements, 1):
        print(f"Statement {idx}:\n{statement}\n{'-'*80}")
except SQLParsingError as e:
    print(f"Error parsing SQL: {e}")
```

**Comment by Andersson007** [comment] 2024-10-30 10:24
@felipenazario thanks for explaining your point

1. the postgresql_query module accepts a list of queries and returns results of all of them:
```
- name: Run several queries against acme db
  community.postgresql.postgresql_query:
    db: acme
    query:
    - SELECT version()
    - SELECT id FROM accounts
```
2. what do the other maintainers / community people think cc @hunleyd @betanummeric @aleksvagachev @jchancojr  and others?
I personally don't see a strong reason to make the _script module much more complex and resp error-prone which will increase the maintenance burned (we don't have lots of maintainers) especially considering the fact that the `postgresql_query` module supports multiple queries and returns results of all the queries in return values. I think the `lookup` and other plugins can be used to extract the queries from files and pass them as a list to `_query` when users need the results

**Comment by betanummeric** [comment] 2024-11-02 12:59
I agree with @Andersson007 and would keep the module as-is.
Providing multiple results from a single input string would require pretty complex SQL parsing to split them up and catch every edge case, which I don't think is worth the effort.

@felipenazario I guess you know how _your_ queries look like, so could split them up with some simpler logic fitting your usecase and then send them to `community.postgresql.postgresql_query`.

**Comment by Andersson007** [comment] 2024-11-07 10:11
As other maintainers are for keeping things simple, I'll close the issue
@felipenazario please continue reporting the ideas, it's much appreciated! It's OK that sometimes there's no support for some, but it's good anyway, keep us re-thinking stuff:)
Thanks everyone!

**Closed by Andersson007** 2024-11-07 10:11 UTC
