### ISSUE TITLE
Unable to dynamically use/substitute positional_args to NULLs in postgresql_query

### ISSUE THREAD

**Issue by Iridescens** [ansible-collections/community.postgresql#31] opened 2020-12-16 11:07 UTC
##### SUMMARY

Unable to dynamically use/substitute positional_args to NULLs in postgresql_query

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.general.postgresql_query

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Apr 16 2020, 01:36:27) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

postgresql11-server-11.9-1PGDG.rhel7.x86_64
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"

##### STEPS TO REPRODUCE

Try to dynamically upsert some NULLs into tables

```yaml
community.general.postgresql_query:
        login_host: "{{ awx_request_audit_db_host }}"
        login_user: "{{ awx_request_audit_db_user }}"
        login_password: "{{ awx_request_audit_db_pass }}"
        db: "{{ awx_request_audit_db_name }}"
        query: >
          INSERT INTO request_id_table(request_id)
           VALUES (%s) ON CONFLICT ON CONSTRAINT request_id_table_pk DO NOTHING;
          INSERT INTO requests(request_id,device_hostname,request_type,error_step,config_snapshot,awx_user_name)
           VALUES (%s,%s,%s,%s,%s,%s) ON CONFLICT ON CONSTRAINT requests_pk DO UPDATE
           SET error_step=NULL, config_snapshot=EXCLUDED.config_snapshot, awx_user_name=EXCLUDED.awx_user_name;
          INSERT INTO add_bd_table(request_id,bd_id,bd_vni_id,bd_routedist,bd_subinterface,bd_vlan_id,bd_if_encap)
           VALUES (%s,%s,%s,%s,%s,%s,%s) ON CONFLICT ON CONSTRAINT add_bd_table_pk DO UPDATE
           SET bd_vni_id=EXCLUDED.bd_vni_id,bd_routedist=EXCLUDED.bd_routedist,bd_subinterface=EXCLUDED.bd_subinterface,bd_vlan_id=EXCLUDED.bd_vlan_id,bd_if_encap=EXCLUDED.bd_if_encap;
        positional_args:
          - '{{ request_id }}'
#          - requests
          - '{{ request_id }}'
          - '{{ inventory_hostname }}'
          - '{{ request_type[inventory_hostname] }}'
#          - '{{ error_step[inventory_hostname] }}'
          - NULL
          - '{{ backup_contents_b64.stdout }}'
          - '{{ awx_user_name }}'
#          add_bd_table
          - "{{ request_id }}"
          - "{{ bd_id }}"
          - "{{ bd_vni_id }}"
          - "{{ bd_routedist }}"
          - "{{ bd_subinterface }}"
          - "{{ bd_vlan_id if (bd_vlan_id is defined) else 'NULL' | default('NULL') }}"
          - "{{ bd_if_encap if (bd_if_encap is defined) else 'NULL' | default('NULL') }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

Being able to provide dynamically assigned NULLs

##### ACTUAL RESULTS

While static NULL (after `#          - '{{ error_step[inventory_hostname] }}'`) does get upserted properly, variables upsert 'NULL' into table or '' (empty string), if used without quotes (just NULL, not 'NULL').
I have searched for the clues in ansible examples and SO with no avail. It is highly likely that I am missing some crucial basic Ansible knowledge, but I just can't find it (or using wrong keywords).

```paste below

```

**Comment by Andersson007** [comment] 2020-12-16 12:23
@Iridescens thanks for reporting the issue!

if you use `- null`, it works OK? https://github.com/ansible-collections/community.postgresql/pull/32

**Comment by Iridescens** [comment] 2020-12-16 14:37
@Andersson007 Yes, that explicit static definition works (i stated that in 'ACTUAL RESULTS'). As it seems case-insensitive, it accepts `null` as well as `NULL`.
I would be grateful if you could provide me a how-to with dynamic ansible variables.

**Comment by Andersson007** [comment] 2020-12-17 10:05
ah, you mean `- "{{ bd_if_encap if (bd_if_encap is defined) else 'NULL' | default('NULL') }}"`
i see now.
I tried several options of null - the same result, it's substituted with "".
for example,
```
 18   - name: Debug
 19     debug:
 20       msg: "{{ error_step if (error_step is defined) else none | default(none) }}"

ok: [spblnx124] => {
    "msg": ""
}
```
It's not a bug of the module. I don't know the solution, I think it relates to how jinja2 works. Maybe anybody else knows workarounds.

**Comment by Andersson007** [comment] 2020-12-17 10:15
I come up with a workaround^
```
 19   - name: When undefined
 20     set_fact:
 21         error_step: NULL
 22     when: error_ster is undefined
 23 
 24   - name: Debug
 25     debug:
 26       msg: '{{ error_step }}'

ok: [spblnx124] => {
    "msg": null
}
```

**Comment by Andersson007** [comment] 2020-12-17 11:13
Added an example to the doc https://github.com/ansible-collections/community.postgresql/pull/32

**Comment by felixfontein** [comment] 2020-12-19 16:21
This can be fixed by enabling Ansible's [`DEFAULT_JINJA2_NATIVE` configuration](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#default-jinja2-native), see also https://github.com/ansible/ansible/issues/73010#issuecomment-747445941.

**Comment by Andersson007** [comment] 2020-12-21 06:32
@felixfontein thanks for the clue! As the tests passed https://github.com/ansible-collections/community.postgresql/pull/32 , I'll merge the PR and will close the issue.

**Comment by Andersson007** [comment] 2020-12-21 07:18
@Iridescens thanks for reporting the issue!

**Closed** 2020-12-21 07:17 UTC

**Comment by Iridescens** [comment] 2020-12-23 15:47
Sorry for being late to the talk, but I confirm that setting `jinja2_native = True` to `ansible.cfg` made the following code correctly preserve and upsert the NULLs:
```
          - "{{ bd_vlan_id if (bd_vlan_id is defined) else None | default(None) }}"
          - "{{ bd_if_encap if (bd_if_encap is defined) else None | default(None) }}"
```
At this time I didn't observe any unexpected behavior from setting jinja2_native.
@felixfontein Thank you very much! Happy holidays!

**Comment by felixfontein** [comment] 2020-12-23 21:07
@Iridescens thanks for verifying that! I think I'll also definitely flip that switch for my playbooks. Have to test whether there are some potential changes first of course, but I don't think there should be (otherwise I would treat that as bugs).

Also happy holidays to you!

**Comment by Andersson007** [comment] 2020-12-24 05:45
@Iridescens thanks for the feedback and confirmation!
