### ISSUE TITLE
community.postgresql.postgresql_pg_hba [3.8.0] Problem "has host bits set"

### ISSUE THREAD

**Issue by anvgarifullin** [ansible-collections/community.postgresql#774] opened 2024-11-22 11:20 UTC
##### SUMMARY
When working with the configured pg_hba.conf, I get the error ("changed": false, "msg": "Error reading file:\nError in line 88: 127.0.0.1/28 has host bits set"). This happens if the host byte is set, although it is expected to be 0. Before that, we were working with version 3.4.0 and there was no such error. There was no error when installing 3.4.0.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.postgresql.postgresql_pg_hba

##### ANSIBLE VERSION
```
ansible --version
ansible [core 2.17.6]
python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
jinja version = 3.0.3
```

##### OS / ENVIRONMENT
Ubuntu 22.04

##### STEPS TO REPRODUCE
pg_hba.conf contains the ip 127.0.0.1/28:
  host    all     username 127.0.0.1/28    trust

```yaml
- name: Edit pg_hba
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  community.postgresql.postgresql_pg_hba:
    dest: "{{ hba_path }}"
    address: "{{ hostvars[groups['monitoring_server'][0]]['ansible_default_ipv4']['address'] }}/32"
    backup: true
    contype: host
    databases: "{{ gp_base }}"
    method: md5
    state: present
    users: "{{ gp_user }}"
```

##### EXPECTED RESULTS
It works without error or is there a parameter to disable strict mode as in python.ipaddress.IPv4Network(address, **strict=True**)

##### ACTUAL RESULTS
{"changed": false, "msg": "Error reading file:\nError in line 88: 127.0.0.1/28 has host bits set"}

**Comment by toydarian** [comment] 2024-11-22 11:57
You get the error, because there are host-bits set on the range `127.0.0.1/28`. The correct one would be `127.0.0.0/28` for the whole range or if you want only `127.0.0.1`, you would need to use `127.0.0.1/32`.

As you have an incorrect range and it is not clear what the intention is, you get this error. Disabling strict-mode will change the range to `127.0.0.0/28` which might not be what you want and might open your rule to a larger range of IPs than what you expect.

I suggest you remove the faulty rules from your `pg_hba.conf` file.

**Comment by Andersson007** [comment] 2024-11-25 07:17
@anvgarifullin thanks for reporting the issue!
@toydarian thanks for explaining how to solve it.
Closing as complete

**Comment by V-Laeda** [comment] 2024-11-25 08:24
Hello!

I am a colleague of @anvgarifullin and searched for the reason together with him.

And we can't confirm that the issue is resolved.

The fact is that we automate the settings of already installed and partially configured systems, and if these systems are satisfied with their configuration, but our automation is not satisfied, then this becomes our problem.

That is, Postgres is satisfied that in its configuration, host address instead of the subnet address, so the system is configured before us and without our participation. Next, we take steps to configure other parts of the system, and our automation crashes because it doesn't like what is already working, and to start Ansible, we are asked to fix the working config to another working config so that Ansible can work?

This is strange to say the least. And if we need to set up hundreds of hosts, and each of them has a file with hundreds of "wrong" (actually normal) addresses — do you suggest correcting all 10,000 entries manually?

Temporary (_I hope_) workaround: specified the old version of `community.postgresql` in `requirements.yml`: `3.4.0`.

**Comment by Andersson007** [comment] 2024-11-25 08:41
@V-Laeda hello, thanks for the feedback. I've re-open the issue to get the others' opinions on your comment, thanks!

**Comment by hunleyd** [comment] 2024-11-25 14:06
> @V-Laeda hello, thanks for the feedback. I've re-open the issue to get the others' opinions on your comment, thanks!

i'm with @toydarian on this one. the module (now) does the right thing

**Comment by Andersson007** [comment] 2024-11-25 14:31
thanks for the feedback folks

**Closed by Andersson007** 2024-11-25 14:31 UTC
