### ISSUE TITLE
postgresql_user not idempotent when user privilege set to pg_stat_database:SELECT

### ISSUE THREAD

**Issue by zyitingftnt** [ansible-collections/community.postgresql#122] opened 2021-08-10 18:51 UTC
##### SUMMARY
postgresql_user module keeps reporting "changed" state for existing postgresql user whose privilege set to **pg_stat_database:SELECT**

However, if I set privilege value to **ALL**, then problem goes away.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
postgresql_user module

##### ANSIBLE VERSION

```
bash-4.4# ansible --version
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### COLLECTION VERSION
```
root@server$ ansible-galaxy collection list community.general

# /root/ansible_collections
Collection        Version
----------------- -------
community.general 2.4.0  
```

##### CONFIGURATION
```
root@server$ ansible-config dump --only-changed
COLLECTIONS_PATHS(/root/ansible.cfg) = ['/root/ansible_collections']
DEFAULT_HOST_LIST(/root/ansible.cfg) = ['/root/inventory.ini']
DEFAULT_ROLES_PATH(/root/ansible.cfg) = ['/etc/ansible/roles', '/root/roles']
```

##### OS / ENVIRONMENT
```
CentOS 7
Ansible AWX 16.0.0
```

##### STEPS TO REPRODUCE
```
1. run playbook to create user
2. run the same playbook again
```

##### EXPECTED RESULTS
The task shows OK

##### ACTUAL RESULTS
The task about the user whose priv set to pg_stat_database:SELECT keeps showing "changed" while other users whose priv set to ALL do not have the problem and their states are "OK"

```
master playbook call the task "postgresql_manage_user" from role "postgresql"
---
- name: update postgresql users on standalone or global master
  hosts: "{{ target | default('harbor_all_pgsql') }}"
  gather_facts: true
  remote_user: root
  tasks:
    - include_role:
        name: postgresql
        tasks_from: postgresql_manage_user


task "postgresql_manage_user" playbook as below:
---
- name: update PostgreSQL users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    role_attr_flags: "{{ item.role_attr_flags | default(omit) }}"
    db: "{{ item.db | default(omit) }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_password: "{{ item.login_password | default(postgresql_pass) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_users }}"
  become: true
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true


"postgresql_users" variable contains 3 users as below, the one whose priv set to is the one with non-idempotent problem.
postgresql_users:
  - name: user1
    password: XXXX
    encrypted: yes
    db: postgres
    priv: ALL
    state: present
  - name: user2
    password: XXXX
    encrypted: yes
    db: postgres
    priv: ALL
    state: present
  - name: user3
    password: XXXX
    encrypted: yes
    db: postgres
    priv: pg_stat_database:SELECT   <---------------------------------------------------------
    state: present 
```

**Comment by Andersson007** [comment] 2021-08-11 09:03
@zyitingftnt thanks for the issue! I'll try to reproduce this in our integration tests ASAP

**Comment by Andersson007** [comment] 2021-08-11 10:01
I reproduced this, the bug exists.
I added:
```
753   ########################################################################
754   # https://github.com/ansible-collections/community.postgresql/issues/122
755 
756   - name: Create role with SELECT
757     <<: *task_parameters
758     postgresql_user:
759       <<: *pg_parameters
760       name: 'issue122'
761       priv: 'pg_stat_database:SELECT'
762     register: result
763 
764   - assert:
765       that:
766       - result is changed
767 
768   - name: Create role with SELECT again
769     <<: *task_parameters
770     postgresql_user:
771       <<: *pg_parameters
772       name: 'issue122'
773       priv: 'pg_stat_database:SELECT'
774     register: result
775 
776   - assert:
777       that:
778       - result is not changed
```
and the second assert fails. Same result with `pg_stat_database:UPDATE`.
@zyitingftnt thanks!

**Comment by Andersson007** [comment] 2021-08-11 10:02
@tcraxs you have experience in working with the priv-related stuff, do you have any ideas why this happens?
Any help with fixing the bug would be much appreciated.

**Comment by Andersson007** [comment] 2021-08-13 06:36
i investigated a bit:
1. Run the same in ansible 2.9 - same result
2. Looked through the backports - nothing related was backported

This means that the bug was there for years... Strange that nobody reported this earlier

**Comment by Andersson007** [comment] 2021-08-13 07:56
i figured out why, preparing the answer now

**Comment by Andersson007** [comment] 2021-08-13 09:08
@zyitingftnt the table is the key in this case.
If a schema is not passed, the module uses `public` by default when getting current grants.
The module would use the following query to get grants in our case:
```
SELECT privilege_type FROM information_schema.role_table_grants WHERE grantee='issue122' AND table_name='pg_stat_database' AND table_schema='public'
```
And it will return nothing because the schema of `pg_stat_database` is `pg_catalog`.
If you pass `pg_catalog.pg_stat_database:SELECT` instead of `pg_stat_database:SELECT` everything should be fine.

I created a PR clarifying the related documentation https://github.com/ansible-collections/community.postgresql/pull/124.
Could you please take a look, try, and give feedback?

IMPORTANT: yeah, i agree, it's confusing. But if i change the way the module works with this (say, if we append `public` when granting if a schema is not passed in privs) it would make things consistent but it can also break a lot, i.e. backwards compatibility. That's why i'm in favor of clarifying the doc without touching the code.

**Comment by Andersson007** [comment] 2021-08-13 09:13
So nothing actually strange that nobody reported it so far because this is quite a corner case. In most cases everything works perfect when users omit the schema part.

**Comment by zyitingftnt** [comment] 2021-08-13 09:18
@Andersson007 You rocks! I just tried your solution by using the` pass pg_catalog.pg_stat_database:SELECT` instead of `pg_stat_database:SELECT`, it is idempotent now! Thank you very much, the idempotency is crucial for me.

So, if i understand correctly, when setting the value to priv, I need to specify the schema along with the table?

**Comment by Andersson007** [comment] 2021-08-13 09:22
@zyitingftnt you're welcome! yeah, when the schema is not `public`.
So i think we can merge the PR and close the issue?

**Comment by zyitingftnt** [comment] 2021-08-13 09:23
> @zyitingftnt you're welcome! yeah, when the schema is not `public`.
> So i think we can merge the PR and close the issue?

Yeah, I think so :) thanks again!

**Comment by Andersson007** [comment] 2021-08-13 09:26
If you approve the PR it would be nice: "Files changed" tab above the description -> "Review changes" green button -> "Approve".
Thanks for the issue, it helped clarify the doc and invent a very useful return value which is very helpful for debugging!

**Closed** 2021-08-13 09:31 UTC
